name: Despliegue a producci贸n

on:
  push:
    branches:
      - main

jobs:
  despliegue:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del c贸digo
      uses: actions/checkout@v2
      
    - name: Instalar dependencias
      run: npm install
      
    - name: Compilar aplicaci贸n
      run: npm run build
      
    - name: Desplegar a producci贸n
      run: |
        ssh usuario@servidor 'bash -s' < deploy.sh